import shutil
from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import RedirectResponse
from fastapi.staticfiles import StaticFiles

from app.config import settings
from app.database import init_db
from app.routers import datasets, export, processing, results

# Compiled Next.js static output (generated by: cd frontend && npm run build)
FRONTEND_OUT = Path(__file__).resolve().parent.parent.parent / "frontend" / "out"


def _create_rsc_stubs() -> None:
    """Create __next.<page>.__PAGE__.txt stubs so App Router prefetch 404s don't fire."""
    if not FRONTEND_OUT.exists():
        return
    for page_dir in FRONTEND_OUT.iterdir():
        if not page_dir.is_dir() or page_dir.name.startswith("_"):
            continue
        index_txt = page_dir / "index.txt"
        if not index_txt.exists():
            continue
        target = page_dir / f"__next.{page_dir.name}.__PAGE__.txt"
        if not target.exists():
            shutil.copy2(index_txt, target)


@asynccontextmanager
async def lifespan(app: FastAPI):
    await init_db()
    _create_rsc_stubs()
    yield


app = FastAPI(
    title="Metaverse User Profiling API",
    version="1.0.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── API routers  (/api/…) — registered first so they take priority ────────────
app.include_router(datasets.router)
app.include_router(processing.router)
app.include_router(results.router)
app.include_router(export.router)


@app.get("/health")
async def health():
    return {"status": "ok"}


# Root redirect — serves upload page immediately without waiting for JS
@app.get("/", include_in_schema=False)
async def root():
    return RedirectResponse("/upload/", status_code=307)


# ── Uploaded images (/uploads/…) ─────────────────────────────────────────────
app.mount("/uploads", StaticFiles(directory=str(settings.upload_dir)), name="uploads")

# ── Frontend static files — html=True serves index.html for directories ───────
# This MUST be mounted LAST so API routes above are matched first.
if FRONTEND_OUT.exists():
    app.mount("/", StaticFiles(directory=str(FRONTEND_OUT), html=True), name="frontend")
